# -----------------------------
# Frontend Deployment & Service
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 522814695006.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:5000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      imagePullSecrets:
      # ✅ Correct placement
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # Change to LoadBalancer for AWS if needed
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
